### ISSUE TITLE
Left-sided window buttons not present

### ISSUE THREAD

**Issue by TheSorceressofOs** [FineFindus/Hieroglyphic#11]
Hi,
on gnome when you set the window button (close,minimize, etc.) layout to the left, the buttons won't be there:

![image](https://github.com/FineFindus/Hieroglyphic/assets/64553635/ca555a94-e057-4451-8f4f-125e42e3f9c5)

Thanks:)

**Comment by FineFindus** [comment]
Thanks for the report. 
I've opened an [issue in libadwaita](https://gitlab.gnome.org/GNOME/libadwaita/-/issues/831), since I suspect that this is not intended behavior.
