### ISSUE TITLE
Unicode mode?

### ISSUE THREAD

**Issue by nclm** [FineFindus/Hieroglyphic#14]
I know this is for Latex, but I could really use a Unicode version of this app :) And I feel many more people need Unicode symbols on a daily basis than Latex symbols.

What would it take to a Unicode mode for the app? Exactly the same, but it would copy the Unicode symbol instead. Just a switch to activate one mode or the other. Maybe when opening the app for the first time, it would ask you which mode you want to use.

It would be really cool as a local native version of shapecatcher.com!

**Comment by FineFindus** [comment]
Thanks for the suggestion, but this is out of scope. It would fit much better in [Characters](https://apps.gnome.org/Characters/) since they already deal with searching for Unicode characters.
