### ISSUE TITLE
Unable to push translations via Damned Lies

### ISSUE THREAD

**Issue by rffontenelle** [FineFindus/Hieroglyphic#31]
When using "send to the repository" action to push translations via Damned Lies, I get:

>  An error occurred during applying your action: The commit failed. The error was: “[Errno 128] Command: ‘['git', 'push', 'origin', 'main']’, Error: Warning: Permanently added 'github.com' (ED25519) to the list of known hosts. ERROR: Permission to FineFindus/Hieroglyphic.git denied to gnomeinfra-github. fatal: Could not read from remote repository. Please make sure you have the correct access rights and the repository exists. ”

Clearly the account used by Damned Lies to push translations to GitHub repositories does not have write access for pushing translations to this one. It would be easier for the language team coordinators and committers if this feature was working in here too to avoid needing to open pull requests.

**Comment by FineFindus** [comment]
I'm aware, we are tracking the issue on the GNOME GitLab: https://gitlab.gnome.org/Infrastructure/damned-lies/-/issues/543#note_2226252

**Comment by rffontenelle** [comment]
> An error occurred during applying your action: O commit falhou. O erro foi: “Command '['git', 'push', 'origin', 'main']' returned non-zero exit status 128.”. 

Different message, I assume something changed 🤔

**Comment by FineFindus** [comment]
I haven't head anything back, but I guess that means we're making progress :)

**Comment by rffontenelle** [comment]
It does seem so. Can you confirm the GNOME account accepted your invite?

**Comment by FineFindus** [comment]
No, the invite for gnomeinfra-github account is still pending, so really not sure what has changed.

**Comment by jtux270** [comment]
Can confirm the error “Command '['git', 'push', 'origin', 'main']' returned non-zero exit status 128” is still present (Russian team om DL).  There are 3 issues already on GNOME GitLab mentioning those errors, added myself to #1699[1] to stay informed.

[1]https://gitlab.gnome.org/Infrastructure/Infrastructure/-/issues/1699

**Comment by FineFindus** [comment]
Closing as the issue should be fixed and pushing translation is now possible.
