### ISSUE TITLE
SVG icon has a black background in KDE

### ISSUE THREAD

**Issue by archisman-panigrahi** [FineFindus/Hieroglyphic#38]
For some reason, the hieroglyphic svg icon has a black background in KDE menu and file manager. The issue is present in every KDE systems I have tried, in different operating systems (Ubuntu, KDE Neon, Arch). But the issue is absent when I open it in inkscape. 

This issue only appears in KDE but not in GNOME. The issue was **inherited** from the TeX Match icon.

The solution is to create a fresh SVG file and copy paste the contents of the icon into a new file with same document size in inkscape (PR coming soon), so the problematic background is not copied.

![image](https://github.com/user-attachments/assets/7d1e0ac8-d5a1-4963-8a72-bb8e6908d408)
(In KDE Menu)

![image](https://github.com/user-attachments/assets/91dc8125-ee54-4a35-9c9f-3bf9fb60dd91)
(Black background of icons in the file manager)

![image](https://github.com/user-attachments/assets/96e0337a-ef0e-484f-b476-0ccd6353127d)

(black background of icon in the launcher in panel)

**Comment by FineFindus** [comment]
Thanks for the report. I think it's worthwhile to also create an issue on the KDE side, since it shouldn't render transparency black.
Does this also occur with other GNOME apps?

cc @bertob: I think you've made both the TeX Match and the Hieroglyphic icon, any idea what could cause that/if that's an issue of the icon?

**Comment by bertob** [comment]
I don't think we're doing anything special here, it's a pretty standard icon exported via App Icon Preview. If the problem happens here it should happen with every other GNOME icon as well...

**Comment by FineFindus** [comment]
This is a [KDE bug, that affects all (third-party) icons](https://bugs.kde.org/show_bug.cgi?id=448234), as their SVG renderer does not support clip paths.
