### ISSUE TITLE
Main window doesn't grab focus on startup

### ISSUE THREAD

**Issue by gregorni** [FineFindus/Hieroglyphic#7]
When building the app in GNOME Builder, it doesn't open in front of other apps the way one would expect it to.

**Comment by FineFindus** [comment]
Hmm, I can't replicate it. It opens correctly for me in front of other apps, it just takes some time (which is not intended, but another bug :)).

**Comment by tchx84** [comment]
I can't reproduce this either on:

* Fedora 39 Silverblue
* Flatpak 1.15.6
* Hieroglyphic 1.0.1 from Flathub

**Comment by gregorni** [comment]
On `main`, the issue is fixed for me now. Not sure what the problem was 🤷
